### ISSUE TITLE
MainClauseVerb in cariban_constructions.csv must be non-empty

### ISSUE THREAD

**Issue by xrotwang** [cldf-datasets/mattercariban#1]
See https://github.com/cldf-datasets/mattercariban/commit/f2982a97463547c2e35b918fdf4fe7bd2580259e#r42189053

**Comment by fmatter** [comment]
Fixed with [86da82ba60f37d10c6ca303a48ba70c5cc62cc9e](https://github.com/cldf-datasets/mattercariban/commit/86da82ba60f37d10c6ca303a48ba70c5cc62cc9e)
