### ISSUE TITLE
Implement cldfbench script to create release version of the dataset

### ISSUE THREAD

**Issue by xrotwang** [cldf-datasets/mattercariban#3]

**Comment by LinguList** [comment]
Is there a plan to segmentize data and make a lexibank dataset out of the Swadesh list and potentially other lexical items?

**Comment by xrotwang** [comment]
@fmatter what do you think about segmentation?

**Comment by fmatter** [comment]
Can do, I already have orthography profiles for all languages. Where can I find an example of the current workflow?

**Comment by xrotwang** [comment]
I can setup the machinery. As far as I can tell, this would be a pure
lexical dataset, right? So no need for two CLDF datasets with different
modules?

Florian Matter <notifications@github.com> schrieb am Fr., 11. Sep. 2020,
11:22:

**Comment by fmatter** [comment]
>  As far as I can tell, this would be a pure
lexical dataset, right? So no need for two CLDF datasets with different
modules?

The Swadesh list data set would be purely lexical, yes -- but there would still be the CLDF dataset with grammatical information, no?

**Comment by xrotwang** [comment]
The question is whether the data is "grammatical enough" to make a combination of one CLDF Wordlist + one CLDF StructureDataset more useful than just a CLDF Wordlist augmented with the data like constructions, etc.
Since we don't have much support for constructions in the CLDF StructureDataset spec so far, and since we don't have any simple questionaire-like "language-feature-value" data here, I'd opt for the CLDF Wordlist.

**Comment by LinguList** [comment]
@fmatter, if you want me to check your orthoprofiles, place them for individual languages in `etc/orthography/language_id.tsv` (use speaking identifiers for the names, as you would in `etc/languages.tsv`), and a full profile for all in `etc/orthography.tsv`. Also, you can already place a list of concepts with links to concepticon (if you have them already) in `etc/concepts.tsv`, we will see how "purely" they reflect Swadesh.

**Comment by fmatter** [comment]
> The question is whether the data is "grammatical enough" to make a combination of one CLDF Wordlist + one CLDF StructureDataset more useful than just a CLDF Wordlist augmented with the data like constructions, etc.
> Since we don't have much support for constructions in the CLDF StructureDataset spec so far, and since we don't have any simple questionaire-like "language-feature-value" data here, I'd opt for the CLDF Wordlist.

Yes, that makes sense to me. My question is whether the grammatical data should be included in a lexibank dataset?

**Comment by xrotwang** [comment]
Yes, including the grammatical info would make sense, I think. "lexibank dataset" basically means a "better" CLDF Wordlist, and part of "better" in this case would be info about paradigms and constructions that lexical forms are used in.

**Comment by fmatter** [comment]
> Yes, including the grammatical info would make sense, I think. "lexibank dataset" basically means a "better" CLDF Wordlist, and part of "better" in this case would be info about paradigms and constructions that lexical forms are used in.

Ah -- the lexical forms are in no way connected to the paradigms and constructions within the CLDF data set. They belong to a separate part of my thesis, a [phylogenetic classification](https://gitlab.com/florianmatter/cariban_phylo/). That also uses part of the grammatical data, but the lexical and grammatical data are in principle distinct from one another.

**Comment by xrotwang** [comment]
Ah, ok. In that case we might opt for the two-datasets option. That's a bit
trickier to setup. But still possible. Will do.

Florian Matter <notifications@github.com> schrieb am Fr., 11. Sep. 2020,
15:43:

**Comment by fmatter** [comment]
> @fmatter, if you want me to check your orthoprofiles, place them for individual languages in `etc/orthography/language_id.tsv` (use speaking identifiers for the names, as you would in `etc/languages.tsv`), and a full profile for all in `etc/orthography.tsv`. Also, you can already place a list of concepts with links to concepticon (if you have them already) in `etc/concepts.tsv`, we will see how "purely" they reflect Swadesh.

I just have .csv files with a column `IPA` (for all languages) and a column `Ortho` (for most languages). The lexical data is already fully transcribed in IPA, so no conversion needed!

I can use `segments` to generate phonemically segmented versions, but I'm still not sure what the proper workflow is. I've uploaded an [example profile](https://github.com/cldf-datasets/mattercariban/blob/master/etc/orthography/mac.csv) -- what do I do with this, and more importantly: what should be the end result?

**Comment by xrotwang** [comment]
@fmatter  Have a look at https://github.com/cldf-datasets/mattercariban/pull/6

**Comment by fmatter** [comment]
> @fmatter Have a look at #6

Oh, that was just one profile, for Macushi. Should we not need to use different profiles for different languages? How would I do that? Also, the original orthography is not needed, as far as I can tell? That would be good, because different sources uses different orthographies for the same language. Should I just create single-column csv files, one for each language? But how are they assigned? Via an additional column in `orthography.tsv`? Sorry for all the questions.

**Comment by xrotwang** [comment]
Ah, sorry. Will update accordingly.

**Comment by xrotwang** [comment]
@fmatter just updated the PR, see https://github.com/cldf-datasets/mattercariban/pull/7

**Comment by xrotwang** [comment]
needs to be enhanced to include more data, but this can happen for v1.0
