### ISSUE TITLE
How to handle dialects?

### ISSUE THREAD

**Issue by fmatter** [cldf-datasets/mattercariban#8]
So Akawaio (`aka`) and Ingarikó (`ing`) are both clearly dialects of Kapón. Is there a way to automatically merge the entries to have the language ID `kap`? This is done for the CLLD app; how would that be properly implemented here? Somewhere in lexibank_mattercariban.py?

Similarly, the entries for Upper Xingu Carib are all from the Kuikuro dialect, but in the CLLD app they're listed under `uxc`.

**Comment by LinguList** [comment]
I do not recommend to merge dialects when working with cognate sets.
This is increasing a lot of noise.

**Comment by fmatter** [comment]
OK, I've instead renamed the orthography profiles.
