### ISSUE TITLE
How to give personal communication as a source?

### ISSUE THREAD

**Issue by fmatter** [cldf-datasets/mattercariban#9]
Some items stem from personal communication; this is originally coded as `pc[FirstName LastName]` -- how should I do this? Add a mock entry to the bibfile, or is there a proper way?

**Comment by xrotwang** [comment]
For such cases, I'd add a separate column `Source_Comment` or similar. This is also the reason, the `clld` data model has text fields like [`source`](https://github.com/clld/clld/blob/ee50ef2bc40c27e28343d87c5a246c529f0b1f16/src/clld/db/models/valueset.py#L44) in addition to proper relations to `Source` objects.

**Comment by fmatter** [comment]
So the `Source` column would then be specified as not obligatory in the
JSON file, right?


On 25 September 2020 at 07:36:29, Robert Forkel (notifications@github.com)
wrote:

For such cases, I'd add a separate column Source_Comment or similar. This
is also the reason, the clld data model has text fields like source
<https://github.com/clld/clld/blob/ee50ef2bc40c27e28343d87c5a246c529f0b1f16/src/clld/db/models/valueset.py#L44>
in addition to proper relations to Source objects.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/cldf-datasets/mattercariban/issues/9#issuecomment-698730040>,
or unsubscribe

**Comment by xrotwang** [comment]
yes.
